import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();
const d=(day:number)=>new Date(`2026-09-${String(day).padStart(2,"0")}T08:00:00.000Z`);
async function main(){
 await db.commission.deleteMany(); await db.leadActivity.deleteMany(); await db.lead.deleteMany(); await db.referralClick.deleteMany(); await db.affiliate.deleteMany(); await db.program.deleteMany();
 await db.appSetting.upsert({where:{id:"default"},update:{},create:{id:"default",fixedAmount:75000}});
 const programs=await Promise.all([["Ammiyah Saudi Arabia","ammiyah-saudi","Kelas percakapan dengan fokus dialek Saudi Arabia",500000],["Bahasa Arab Percakapan","percakapan","Berani berbicara Bahasa Arab sehari-hari",450000],["Bahasa Arab Dasar","dasar","Fondasi Bahasa Arab yang terarah",400000],["Bahasa Arab Anak","anak","Kelas Bahasa Arab yang ramah anak",350000],["Kelas Privat","privat","Pendampingan belajar personal",750000]].map(([name,slug,description,price])=>db.program.create({data:{name:String(name),slug:String(slug),description:String(description),price:Number(price)}})));
 const affiliates=await Promise.all([["Naufal Nabila","NAUFAL","6281212348454",42],["Ahmad Fauzan","AHMADF","6281398761234",31],["Ummu Maryam","UMMARYAM","6282234567890",24],["Abdullah","ABDULLAH","6285176543210",18],["Alumni Ahlan 01","ALUMNI01","6281144445555",11]].map(([name,code,phone,clicks])=>db.affiliate.create({data:{name:String(name),code:String(code),phone:String(phone),clicks:Number(clicks),createdAt:d(1)}})));
 const rows:[string,number,number,string,number,number?][]=[["Suyadi",0,0,"DIHUBUNGI",12],["Ahmad Pratama",1,0,"LUNAS",3,450000],["Fatimah Zahra",2,1,"DAFTAR",5],["Abdullah Ramli",0,0,"MENUNGGU_PEMBAYARAN",7],["Zaid Akbar",1,2,"LUNAS",9,450000],["Aisyah Rahmi",3,2,"TERTARIK",10],["Fajar Nugroho",2,3,"FOLLOW_UP",11],["Rahma Anjani",0,0,"LUNAS",14,500000],["Yusuf Maulana",4,4,"BATAL",16],["Hana Safitri",1,1,"LEAD_BARU",18],["Nabila Putri",3,0,"DAFTAR",20],["Rizky Hidayat",0,1,"LUNAS",21,400000]];
 for(const [name,p,a,status,day,value] of rows){const lead=await db.lead.create({data:{name,phone:`62812${String(day).padStart(7,"0")}`,city:["Bandung","Jakarta","Depok","Bekasi"][day%4],programId:programs[p].id,affiliateId:affiliates[a].id,source:day===12?"WHATSAPP":"REFERRAL_LINK",status,registrationValue:value,createdAt:d(day),paymentVerifiedAt:status==="LUNAS"?d(day):null,notes:name==="Suyadi"?"Mencari program online. Mendapat info dari Naufal melalui WhatsApp.":null,activities:{create:[{type:"REFERRAL",message:`Referral masuk melalui kode ${affiliates[a].code}`,createdAt:d(day)},{type:"STATUS",message:`Status diperbarui menjadi ${status.replaceAll("_"," ")}`,createdAt:d(Math.min(day+1,28))}]}}}); if(status==="LUNAS"&&value) await db.commission.create({data:{leadId:lead.id,affiliateId:affiliates[a].id,amount:75000,status:name==="Ahmad Pratama"?"PAID":"PENDING",paidAt:name==="Ahmad Pratama"?d(7):null}})}
}
main().finally(()=>db.$disconnect());
