"use server";
import { db } from "@/lib/db";
import { leadSchema } from "@/lib/validation";
import { normalizePhone, calculateCommission, type LeadStatus } from "@/lib/domain";
import { revalidatePath } from "next/cache";
export async function submitLead(form:FormData){const parsed=leadSchema.safeParse(Object.fromEntries(form));if(!parsed.success)return {ok:false,error:parsed.error.issues[0].message};const d=parsed.data,affiliate=d.referralCode?await db.affiliate.findFirst({where:{code:d.referralCode.toUpperCase(),isActive:true}}):null;const lead=await db.lead.create({data:{name:d.name,phone:normalizePhone(d.phone),city:d.city,notes:d.notes||null,programId:d.programId,affiliateId:affiliate?.id,source:affiliate?"REFERRAL_LINK":"DIRECT",activities:{create:{type:"CREATED",message:affiliate?`Referral masuk melalui kode ${affiliate.code}`:"Pendaftaran baru diterima"}}}});if(affiliate)await db.referralClick.create({data:{affiliateId:affiliate.id,refCode:affiliate.code,sessionId:lead.id}});return {ok:true}}
export async function updateLeadStatus(id:string,status:LeadStatus){const lead=await db.lead.findUnique({where:{id},include:{program:true,affiliate:true}});if(!lead)return;const data:{status:string,paymentVerifiedAt?:Date}={status};if(status==="LUNAS")data.paymentVerifiedAt=new Date();await db.lead.update({where:{id},data:{...data,activities:{create:{type:"STATUS",message:`Admin mengubah status menjadi ${status.replaceAll("_"," ")}`}}}});if(status==="LUNAS"&&lead.affiliateId&&!await db.commission.findUnique({where:{leadId:id}})){const s=await db.appSetting.findUnique({where:{id:"default"}}),amount=calculateCommission(lead.registrationValue||lead.program.price,s?.commissionMethod||"FIXED",s?.fixedAmount||75000,s?.percentage||10);await db.commission.create({data:{leadId:id,affiliateId:lead.affiliateId,amount,status:"PENDING"}});await db.leadActivity.create({data:{leadId:id,type:"COMMISSION",message:`Komisi Rp${amount.toLocaleString("id-ID")} dibuat untuk ${lead.affiliate?.name}`}})}revalidatePath("/admin");revalidatePath(`/admin/leads/${id}`);revalidatePath("/admin/leads");revalidatePath("/affiliate")}
export async function updateLeadValue(id:string,value:number){await db.lead.update({where:{id},data:{registrationValue:value,activities:{create:{type:"PAYMENT",message:`Nilai kelas diperbarui menjadi Rp${value.toLocaleString("id-ID")}`}}}});revalidatePath(`/admin/leads/${id}`)}
export async function payCommission(id:string){await db.commission.update({where:{id},data:{status:"PAID",paidAt:new Date()}});revalidatePath("/admin/commissions");revalidatePath("/admin");revalidatePath("/affiliate")}
export async function updateCommissionStatus(id:string,status:string){await db.commission.update({where:{id},data:{status,approvedAt:status==="APPROVED"?new Date():undefined,paidAt:status==="PAID"?new Date():undefined}});revalidatePath("/admin/commissions")}
export async function createAffiliate(form:FormData){const name=String(form.get("name")||"").trim(),code=String(form.get("code")||"").trim().toUpperCase();if(name.length<2||!/^[-A-Z0-9]{3,20}$/.test(code))return {ok:false,error:"Nama atau kode referral belum valid."};try{await db.affiliate.create({data:{name,code,phone:String(form.get("phone")||"")||null}});revalidatePath("/admin/affiliates");return {ok:true}}catch{return {ok:false,error:"Kode referral sudah digunakan."}}}
