import type { Affiliate, Program, Lead, Commission, AppSetting } from "./types";

export const initialPrograms: Program[] = [
  {
    id: "prog-ammiyah-saudi",
    name: "Ammiyah Saudi Arabia",
    slug: "ammiyah-saudi",
    description: "Kelas percakapan dengan fokus dialek Saudi Arabia",
    price: 500000,
    active: true,
  },
  {
    id: "prog-percakapan",
    name: "Bahasa Arab Percakapan",
    slug: "percakapan",
    description: "Berani berbicara Bahasa Arab sehari-hari",
    price: 450000,
    active: true,
  },
  {
    id: "prog-dasar",
    name: "Bahasa Arab Dasar",
    slug: "dasar",
    description: "Fondasi Bahasa Arab yang terarah",
    price: 400000,
    active: true,
  },
  {
    id: "prog-anak",
    name: "Bahasa Arab Anak",
    slug: "anak",
    description: "Kelas Bahasa Arab yang ramah anak",
    price: 350000,
    active: true,
  },
  {
    id: "prog-privat",
    name: "Kelas Privat",
    slug: "privat",
    description: "Pendampingan belajar personal",
    price: 750000,
    active: true,
  },
];

export const initialAffiliates: Affiliate[] = [
  {
    id: "aff-naufal",
    name: "Naufal Nabila",
    code: "NAUFAL",
    phone: "6281212348454",
    email: "naufal@ahlan.id",
    isActive: true,
    clicks: 42,
    createdAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
  },
  {
    id: "aff-ahmadf",
    name: "Ahmad Fauzan",
    code: "AHMADF",
    phone: "6281398761234",
    email: "ahmadf@ahlan.id",
    isActive: true,
    clicks: 31,
    createdAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
  },
  {
    id: "aff-ummaryam",
    name: "Ummu Maryam",
    code: "UMMARYAM",
    phone: "6282234567890",
    email: "ummaryam@ahlan.id",
    isActive: true,
    clicks: 24,
    createdAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
  },
  {
    id: "aff-abdullah",
    name: "Abdullah",
    code: "ABDULLAH",
    phone: "6285176543210",
    email: "abdullah@ahlan.id",
    isActive: true,
    clicks: 18,
    createdAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
  },
  {
    id: "aff-alumni01",
    name: "Alumni Ahlan 01",
    code: "ALUMNI01",
    phone: "6281144445555",
    email: "alumni01@ahlan.id",
    isActive: true,
    clicks: 11,
    createdAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
    updatedAt: new Date("2026-09-01T08:00:00.000Z").toISOString(),
  },
];

export const initialSetting: AppSetting = {
  id: "default",
  commissionMethod: "FIXED",
  fixedAmount: 75000,
  percentage: 10,
  triggerOnPayment: true,
};

const d = (day: number) => new Date(`2026-09-${String(day).padStart(2, "0")}T08:00:00.000Z`).toISOString();

export const initialLeads: Lead[] = [
  {
    id: "lead-suyadi",
    name: "Suyadi",
    phone: "628120000012",
    city: "Depok",
    notes: "Mencari program online. Mendapat info dari Naufal melalui WhatsApp.",
    source: "WHATSAPP",
    status: "DIHUBUNGI",
    registrationValue: 500000,
    paymentVerifiedAt: null,
    createdAt: d(12),
    updatedAt: d(12),
    programId: "prog-ammiyah-saudi",
    affiliateId: "aff-naufal",
    activities: [
      {
        id: "act-suyadi-1",
        type: "REFERRAL",
        message: "Referral masuk melalui kode NAUFAL",
        createdAt: d(12),
        leadId: "lead-suyadi",
      },
      {
        id: "act-suyadi-2",
        type: "STATUS",
        message: "Status diperbarui menjadi Sudah Dihubungi",
        createdAt: d(13),
        leadId: "lead-suyadi",
      },
    ],
  },
  {
    id: "lead-ahmad-pratama",
    name: "Ahmad Pratama",
    phone: "628120000003",
    city: "Jakarta",
    source: "REFERRAL_LINK",
    status: "LUNAS",
    registrationValue: 450000,
    paymentVerifiedAt: d(3),
    createdAt: d(3),
    updatedAt: d(3),
    programId: "prog-percakapan",
    affiliateId: "aff-naufal",
    activities: [
      {
        id: "act-ahmad-1",
        type: "REFERRAL",
        message: "Referral masuk melalui kode NAUFAL",
        createdAt: d(3),
        leadId: "lead-ahmad-pratama",
      },
      {
        id: "act-ahmad-2",
        type: "STATUS",
        message: "Status diperbarui menjadi Lunas",
        createdAt: d(4),
        leadId: "lead-ahmad-pratama",
      },
    ],
  },
  {
    id: "lead-fatimah-zahra",
    name: "Fatimah Zahra",
    phone: "628120000005",
    city: "Depok",
    source: "REFERRAL_LINK",
    status: "DAFTAR",
    createdAt: d(5),
    updatedAt: d(5),
    programId: "prog-dasar",
    affiliateId: "aff-ahmadf",
    activities: [
      {
        id: "act-fatimah-1",
        type: "REFERRAL",
        message: "Referral masuk melalui kode AHMADF",
        createdAt: d(5),
        leadId: "lead-fatimah-zahra",
      },
    ],
  },
  {
    id: "lead-abdullah-ramli",
    name: "Abdullah Ramli",
    phone: "628120000007",
    city: "Bekasi",
    source: "REFERRAL_LINK",
    status: "MENUNGGU_PEMBAYARAN",
    createdAt: d(7),
    updatedAt: d(7),
    programId: "prog-ammiyah-saudi",
    affiliateId: "aff-naufal",
    activities: [
      {
        id: "act-ramli-1",
        type: "REFERRAL",
        message: "Referral masuk melalui kode NAUFAL",
        createdAt: d(7),
        leadId: "lead-abdullah-ramli",
      },
    ],
  },
  {
    id: "lead-zaid-akbar",
    name: "Zaid Akbar",
    phone: "628120000009",
    city: "Bandung",
    source: "REFERRAL_LINK",
    status: "LUNAS",
    registrationValue: 450000,
    paymentVerifiedAt: d(9),
    createdAt: d(9),
    updatedAt: d(9),
    programId: "prog-percakapan",
    affiliateId: "aff-ummaryam",
    activities: [
      {
        id: "act-zaid-1",
        type: "REFERRAL",
        message: "Referral masuk melalui kode UMMARYAM",
        createdAt: d(9),
        leadId: "lead-zaid-akbar",
      },
    ],
  },
  {
    id: "lead-aisyah-rahmi",
    name: "Aisyah Rahmi",
    phone: "628120000010",
    city: "Jakarta",
    source: "REFERRAL_LINK",
    status: "TERTARIK",
    createdAt: d(10),
    updatedAt: d(10),
    programId: "prog-anak",
    affiliateId: "aff-ummaryam",
  },
  {
    id: "lead-fajar-nugroho",
    name: "Fajar Nugroho",
    phone: "628120000011",
    city: "Depok",
    source: "REFERRAL_LINK",
    status: "FOLLOW_UP",
    createdAt: d(11),
    updatedAt: d(11),
    programId: "prog-dasar",
    affiliateId: "aff-abdullah",
  },
  {
    id: "lead-rahma-anjani",
    name: "Rahma Anjani",
    phone: "628120000014",
    city: "Bekasi",
    source: "REFERRAL_LINK",
    status: "LUNAS",
    registrationValue: 500000,
    paymentVerifiedAt: d(14),
    createdAt: d(14),
    updatedAt: d(14),
    programId: "prog-ammiyah-saudi",
    affiliateId: "aff-naufal",
  },
  {
    id: "lead-yusuf-maulana",
    name: "Yusuf Maulana",
    phone: "628120000016",
    city: "Bandung",
    source: "REFERRAL_LINK",
    status: "BATAL",
    createdAt: d(16),
    updatedAt: d(16),
    programId: "prog-privat",
    affiliateId: "aff-alumni01",
  },
  {
    id: "lead-hana-safitri",
    name: "Hana Safitri",
    phone: "628120000018",
    city: "Jakarta",
    source: "REFERRAL_LINK",
    status: "LEAD_BARU",
    createdAt: d(18),
    updatedAt: d(18),
    programId: "prog-percakapan",
    affiliateId: "aff-ahmadf",
  },
  {
    id: "lead-nabila-putri",
    name: "Nabila Putri",
    phone: "628120000020",
    city: "Depok",
    source: "REFERRAL_LINK",
    status: "DAFTAR",
    createdAt: d(20),
    updatedAt: d(20),
    programId: "prog-anak",
    affiliateId: "aff-naufal",
  },
  {
    id: "lead-rizky-hidayat",
    name: "Rizky Hidayat",
    phone: "628120000021",
    city: "Bekasi",
    source: "REFERRAL_LINK",
    status: "LUNAS",
    registrationValue: 400000,
    paymentVerifiedAt: d(21),
    createdAt: d(21),
    updatedAt: d(21),
    programId: "prog-ammiyah-saudi",
    affiliateId: "aff-ahmadf",
  },
];

export const initialCommissions: Commission[] = [
  {
    id: "comm-ahmad-pratama",
    leadId: "lead-ahmad-pratama",
    affiliateId: "aff-naufal",
    amount: 75000,
    status: "PAID",
    generatedAt: d(3),
    approvedAt: d(4),
    paidAt: d(7),
  },
  {
    id: "comm-zaid-akbar",
    leadId: "lead-zaid-akbar",
    affiliateId: "aff-ummaryam",
    amount: 75000,
    status: "PENDING",
    generatedAt: d(9),
  },
  {
    id: "comm-rahma-anjani",
    leadId: "lead-rahma-anjani",
    affiliateId: "aff-naufal",
    amount: 75000,
    status: "PENDING",
    generatedAt: d(14),
  },
  {
    id: "comm-rizky-hidayat",
    leadId: "lead-rizky-hidayat",
    affiliateId: "aff-ahmadf",
    amount: 75000,
    status: "PENDING",
    generatedAt: d(21),
  },
];
